#!/usr/bin/env python3
from __future__ import absolute_import

import os
# Load modules from $JUJU_CHARM_DIR/lib
import sys
sys.path.append(os.path.join(os.getcwd(), 'lib'))

from charms.layer import basic
# This will load and run the appropriate @hook and other decorated
# handlers from $JUJU_CHARM_DIR/reactive, $JUJU_CHARM_DIR/hooks/reactive,
# and $JUJU_CHARM_DIR/hooks/relations.
#
# See https://jujucharms.com/docs/stable/authors-charm-building
# for more information on this pattern.
basic.bootstrap_charm_deps()
basic.init_config_states()

from charms.reactive import main
main()
